### ISSUE TITLE
Update viruslist.txt

### ISSUE THREAD

**Issue by Edouard127** [equati0n/Genome_Antivirus#1]
Hi, i just see your project and i was testing on the virus 000.exe but i scan it and don't detect it, how do i update the file viruslist.txt ?
I take the signature from Windows Defender but still not detect it

**Comment by equati0n** [comment]
The virus list is just a text file. It is in the folder called data. You could add your entry to the file there. I also updated the readme file to include more details about the program.

**Comment by Edouard127** [comment]
Do you have discord or any social media ?

**Comment by Edouard127** [comment]
here my discord: Toxic - Pineapple#1087
